name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install & build frontend
        working-directory: client
        run: |
          npm install
          npm run build

      - name: Install backend
        working-directory: server
        run: npm install

      - name: 'notify vercel'
        if: always()
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: Vercel - edureach
          github_token: ${{ secrets.GITHUB_TOKEN }}